title:              R. Travis Merrill
email:              rtravismerrill@gmail.com
description:        A Curious Mathematician/Statistician
author:              
baseurl:            ""
url:                "https://9TrAvArT9.github.io"

# Social Profiles
twitter_username:   
github_username:    9TrAvArT9
facebook_username:  
instagram_username:  
linkedin_username: rtravismerrill

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
